/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    InfoDialog: typeof import('./src/components/InfoDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticCalendar: typeof import('./src/components/StatisticCalendar.vue')['default']
    TaskForm: typeof import('./src/components/TaskForm.vue')['default']
    TodoCard: typeof import('./src/components/TodoCard.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
